name: tasks_drift
description: Um projeto Flutter para exemplificar o uso de Drift.

publish_to: 'none' 

version: 1.0.0+2 # updated Nov 4th,2024

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  drift: ^2.21.0
  drift_flutter: ^0.1.0
  drift_db_viewer: ^2.1.0
  path_provider: ^2.0.0
  path: ^1.9.0
  
  provider: ^6.1.2
  flutter_slidable: ^3.1.0
  flutter_material_color_picker: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  drift_dev: ^2.21.0
  build_runner: ^2.4.13

flutter:
  uses-material-design: true